# Generated by Django 3.2.16 on 2023-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
