# Generated by Django 3.2.16 on 2023-10-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_discount_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
